### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by brunocalado** [Nachtrose/NRSAP#10]
Hi.

So, you can't use this module in a youtube/twitch game.

Would be possible to change the license to 
![image](https://user-images.githubusercontent.com/4999783/143436335-372a2a7f-82dd-4fe6-befc-de656de4cb1a.png)

**Comment by Nachtrose** [comment]
Ok, i'm not very good at this copyright stuff, but is there any specific issue why not?

**Comment by brunocalado** [comment]
I don't understand it well too.

But, a youtube video or twitch is usually a commercial applicantion. Your license states that you can't use that for it.
![image](https://user-images.githubusercontent.com/4999783/143445641-9bba2e11-2c34-475c-a230-bb42c9572f72.png)

**Comment by Nachtrose** [comment]
I figured that it is this point. I reached to you ( if i connected the dots right ) on FB to discuss it more as it will be somehow faster then here. Or you can reach me on discord as well.

**Comment by Nachtrose** [comment]
Added an exception to the license to allow sponsors, ad revenue donations etc. as long as the following rules are followed:

Exception

Even if this module is licensed under the Non-Commercial license, you are allowed to use it in your streams, videos or simillar ( YouTube, Twitch, etc...) that generates you revenue as long as you adhere to the following rules:

Your project must be free. You’re free to use NRSAP in your project provided that your project is accessible by everyone for free. Free doesn’t just mean free from payment, it also means free from hassle. You can’t require survey completions, gate access behind downloads of unrelated products, require opting in to email lists (unless the entirety of your project is only available in email form), or other unnecessary annoyances as a requirement to access your project. You can’t lock your content behind a paywall of any sort. You are allowed to accept donations on platforms like Patreon and to generate advertising revenue via YouTube, Twitch, and web ads. You are allowed to have paid sponsorship of your content as long as that sponsor is clearly identified to your audience.
