### ISSUE TITLE
Auto Update Macros

### ISSUE THREAD

**Issue by brunocalado** [Nachtrose/NRSAP#12]
Hi.

I add to my modules a little trick so everytime I update a macro the user don't even know. 

I think you could add this to here.

I push 2 macros. One the user should not use. The other one reads the macro in the compendium.
![image](https://user-images.githubusercontent.com/4999783/145618514-32c3158c-8614-49a6-9c80-c720cf9eb800.png)

Snippet
```js
const compediumName = '';
macroRun('MACRO NAME', compediumName);

async function macroRun(macroName, compendiumName='scum-and-villainy-pt-br.macros') {  
  let pack = game.packs.get(compendiumName);
  let macro = ( await pack.getDocuments() ).find(i => (i.data.name==macroName) );
  await macro.execute();    
}
```

**Comment by Nachtrose** [comment]
Included in the v0.1.3.10i release.
