### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [Nachtrose/NRSAP#13]
Hi.

Please remove the foundry vtt warning.
![image](https://user-images.githubusercontent.com/4999783/148384290-d72e496b-d8a0-4ad7-8c5e-4ca76adaa054.png)

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9"

**Comment by Nachtrose** [comment]
Hi,

a fell out of the loop the last few weeks. If all goes well, i will look into it this weekend. I think ist should work no problem on 9+, but i will make a few tests and update accordingly.

**Comment by Aggersboel** [comment]
In v. 0.9 I have found an issue with the soundeffect not stopping correctly, having to refresh. Reverting to v8.9 fixes this.

**Comment by Nachtrose** [comment]
> In v. 0.9 I have found an issue with the soundeffect not stopping correctly, having to refresh. Reverting to v8.9 fixes this.

Does this happen when you run any of the included macros, or if you use the soundeffects as a standalone assets just playing them directly in foundry?

**Comment by Aggersboel** [comment]
It happens when I use the macros included in this module - the sounds and effects plays, when used, but the sound doesn't stop, even though the effects does and the new scene background loads correctly.

**Comment by Nachtrose** [comment]
> It happens when I use the macros included in this module - the sounds and effects plays, when used, but the sound doesn't stop, even though the effects does and the new scene background loads correctly.

Is it all sound effects, or just the effect of the middle part of the hyperspace travel?

**Comment by Aggersboel** [comment]
Just tried it again, saw no errors in log - but to me it sounds like the middle part of the sound effect. The "rumbling", background noice. If I run the macro again, the lingering rumbling "stacks" - until the instance is refreshed.

**Comment by Nachtrose** [comment]
> Just tried it again, saw no errors in log - but to me it sounds like the middle part of the sound effect. The "rumbling", background noice. If I run the macro again, the lingering rumbling "stacks" - until the instance is refreshed.

Ok, i know what to look at now. One last question: do you have your Sequencer addon updated? It's a deppendency, if you want to use the included macros that controls the actual playback and switching of different effects in this case.

**Comment by Nachtrose** [comment]
But thinking about it, the way this specific effect is handled, it shouldn't "stack" no matter what you do.
Maybe it will be really a bug with core Foundry.

**Comment by Aggersboel** [comment]
I can confirm that sequencer is up-to-date. This could of course be a problem there as well, but I have no deeper technical knowledge.

**Comment by Nachtrose** [comment]
> I can confirm that sequencer is up-to-date. This could of course be a problem there as well, but I have no deeper technical knowledge.

No worries. I will check and if i find it might be a Sequencer problem, i get in touch with the author to figure it out.

**Comment by Nachtrose** [comment]
> I can confirm that sequencer is up-to-date. This could of course be a problem there as well, but I have no deeper technical knowledge.

Split this to a separate issue. Bug on foundry's side.

**Comment by Nachtrose** [comment]
Updated for FVTT V9+
