### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by brunocalado** [Nachtrose/NRSAP#15]
Hi.

Can you update to v10?

![image](https://user-images.githubusercontent.com/4999783/194065028-9b22e3b3-6b12-46c4-90a7-bed435e18736.png)

tks

**Comment by Nachtrose** [comment]
It is in the work. With some luck it could drop next week(end).

**Comment by Nachtrose** [comment]
Took longer than expected, but the module is now updated.

**Comment by brunocalado** [comment]
Thank you.
