### ISSUE TITLE
V10 Build 285, Scene becomes stuck/Macro stops working using tile image from outside default folder

### ISSUE THREAD

**Issue by TerallianHub** [Nachtrose/NRSAP#16]
When selecting an image to be used for the background tile, if the image selected is not inside of the default background directory, the scene will become stuck on the looping sequence and the macro will no longer function.

See video attached:

[The Video... Attached](https://streamable.com/sfdjoh)

**Comment by Nachtrose** [comment]
Updated the module for V10 and made some changes on how the background tiles in tile based scenes are identified. You can try it out. Should now work regardless from where you pull your background images.
