### ISSUE TITLE
free pack

### ISSUE THREAD

**Issue by brunocalado** [Nachtrose/NRSAP#6]
Hi. 

I think it's possible to grind something from this:  https://www.premiumbeat.com/blog/space-kit-free-space-elements/

![image](https://user-images.githubusercontent.com/4999783/138572581-a29652a0-f6cc-4eee-9dd1-d747a4f9f397.png)

**Comment by Nachtrose** [comment]
Thanks for pointing this out to me. 
I did check it and it is not usable "as is". Still might prove as a solid base for some work in the future.
