### ISSUE TITLE
Add Planet Pack

### ISSUE THREAD

**Issue by brunocalado** [Nachtrose/NRSAP#8]
Hi.

Are you interested in add a planets pack? You can use them in a item or actor. You can drop them into a star map. 

https://user-images.githubusercontent.com/4999783/139141304-b9cb3d49-4433-41fc-98e6-e61abe5c0ce7.mp4

There is a generator. You can build a lot. I think create a pack could be cool.

drop into maps
[webm.zip](https://github.com/Nachtrose/NRSAP/files/7429097/webm.zip)
use in actors/items
[webp.zip](https://github.com/Nachtrose/NRSAP/files/7429098/webp.zip)

**Comment by Nachtrose** [comment]
Although this is a great idea, i won't include it for two main reasons:
1) it doesn't really fit the art style i am aiming for ( this one is too cartoony )
2) the animations aren't seamless loops
